version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
        - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=items
    ports:
      - "5432:5432"

