kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 4317
        hostPort: 4317
        protocol: TCP
      - containerPort: 4318
        hostPort: 4318
        protocol: TCP
      - containerPort: 3301
        hostPort: 3301
        protocol: TCP
  - role: worker
